
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: geodata
spec:
  refreshInterval: 1h
  secretStoreRef: { kind: ClusterSecretStore, name: vault-backend }
  target: { name: minio-credentials, creationPolicy: Merge }
  data:
  - secretKey: endpoint
    remoteRef: { key: minio/endpoint }
  - secretKey: access_key
    remoteRef: { key: minio/access_key }
  - secretKey: secret_key
    remoteRef: { key: minio/secret_key }
