---
extends: default

ignore: |
  charts/*/templates/*.yaml
  charts/*/templates/*.yml

rules:
  # statt: new-line-at-end-of-file: {present: true}
  new-line-at-end-of-file: enable

  # deine restlichen Regeln:
  line-length: disable
  document-start: disable
  braces:
    max-spaces-inside: 0
  colons:
    max-spaces-after: 1
