---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-proton
  namespace: identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: smtp-proton
    creationPolicy: Merge
  data:
    - secretKey: host        # smtp.protonmail.ch
      remoteRef:
        key: smtp/proton/host
    - secretKey: port        # 587
      remoteRef:
        key: smtp/proton/port
    - secretKey: from
      remoteRef:
        key: smtp/proton/from
    - secretKey: user
      remoteRef:
        key: smtp/proton/user
    - secretKey: password
      remoteRef:
        key: smtp/proton/password
    - secretKey: encryption  # starttls
      remoteRef:
        key: smtp/proton/encryption
