---

provider: hetzner
policy: upsert-only
interval: 1m
sources: ["ingress"]
rbac:
  create: true
serviceAccount:
  create: true
  name: external-dns
env:
  - name: HETZNER_TOKEN
    valueFrom:
      secretKeyRef:
        name: hetzner-token
        key: token
logLevel: info
txtOwnerId: geodata-suite
domainFilters: []